name: herewego
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.2.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.15
  image_picker: ^0.8.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

